INSERT INTO `departments` (`name`,`created_at`,`created_by`) VALUES ('IT', CURDATE(), 'AUTOMATIC_FILL');
INSERT INTO `departments` (`name`,`created_at`,`created_by`) VALUES ('Finance', CURDATE(), 'AUTOMATIC_FILL');
INSERT INTO `departments` (`name`,`created_at`,`created_by`) VALUES ('Marketing', CURDATE(), 'AUTOMATIC_FILL');
INSERT INTO `departments` (`name`,`created_at`,`created_by`) VALUES ('Sales', CURDATE(), 'AUTOMATIC_FILL');
INSERT INTO `departments` (`name`,`created_at`,`created_by`) VALUES ('Engineering', CURDATE(), 'AUTOMATIC_FILL');
INSERT INTO `departments` (`name`,`created_at`,`created_by`) VALUES ('Design', CURDATE(), 'AUTOMATIC_FILL');

INSERT INTO `users` (`first_name`, `last_name`, `job_title`, `email`, `manager`, `password`, `role`, `created_at`, `created_by`, `fk_department_id`) VALUES ('John', 'McCain', 'Help Desk', 'jm@gmail.com', 'Marta', '$2a$10$rgxQE//XV8SZrXuCdsl.AOH.DzSIYnknXysKjbLIQZ7khkWI7emI.', 'ROLE_USER', CURDATE(), 'AUTOMATIC_FILL', '1');
INSERT INTO `users` (`first_name`, `last_name`, `job_title`, `email`, `manager`, `password`, `role`,`created_at`, `created_by`, `fk_department_id`) VALUES ('Ana', 'Pereira', 'Accountant', 'ap@gmail.com', 'Natacha', '$2a$10$rgxQE//XV8SZrXuCdsl.AOH.DzSIYnknXysKjbLIQZ7khkWI7emI.', 'ROLE_USER', CURDATE(), 'AUTOMATIC_FILL', '2');
INSERT INTO `users` (`first_name`, `last_name`, `job_title`, `email`, `manager`, `password`, `role`,`created_at`, `created_by`, `fk_department_id`) VALUES ('Tao', 'Lee', 'Creative', 'tl@gmail.com', 'Leo', '$2a$10$rgxQE//XV8SZrXuCdsl.AOH.DzSIYnknXysKjbLIQZ7khkWI7emI.', 'ROLE_USER', CURDATE(), 'AUTOMATIC_FILL', '3');
INSERT INTO `users` (`first_name`, `last_name`, `job_title`, `email`, `manager`, `password`, `role`,`created_at`, `created_by`, `fk_department_id`) VALUES ('Lin', 'Khoo', 'Video Editor', 'lk@gmail.com', 'Steve', '$2a$10$rgxQE//XV8SZrXuCdsl.AOH.DzSIYnknXysKjbLIQZ7khkWI7emI.', 'ROLE_USER', CURDATE(), 'AUTOMATIC_FILL', '4');
INSERT INTO `users` (`first_name`, `last_name`, `job_title`, `email`, `manager`, `password`, `role`,`created_at`, `created_by`, `fk_department_id`) VALUES ('Patricia', 'Oneil', 'Social Media Specialist', 'po@gmail.com', 'Toni', '$2a$10$rgxQE//XV8SZrXuCdsl.AOH.DzSIYnknXysKjbLIQZ7khkWI7emI.', 'ROLE_USER', CURDATE(), 'AUTOMATIC_FILL', '5');
INSERT INTO `users` (`first_name`, `last_name`, `job_title`, `email`, `manager`, `password`, `role`,`created_at`, `created_by`, `fk_department_id`) VALUES ('Laura', 'Francis', 'System Administrator', 'lf@gmail.com', 'Sanchez', '$2a$10$rgxQE//XV8SZrXuCdsl.AOH.DzSIYnknXysKjbLIQZ7khkWI7emI.', 'ROLE_SUPERUSER', CURDATE(), 'AUTOMATIC_FILL', '1');
INSERT INTO `users` (`first_name`, `last_name`, `job_title`, `email`, `manager`, `password`, `role`,`created_at`, `created_by`, `fk_department_id`) VALUES ('Natacha', 'Kornikova', 'Support Engineer', 'nk@gmail.com', 'Joana', '$2a$10$rgxQE//XV8SZrXuCdsl.AOH.DzSIYnknXysKjbLIQZ7khkWI7emI.', 'ROLE_ADMINISTRATOR', CURDATE(), 'AUTOMATIC_FILL', '1');

INSERT INTO `tickets` (`status`, `subject`, `priority`, `message`, `created_at`, `created_by`,`creator_id`,`assignee_id`,`assignee_derpartment_id`) VALUES ('OPEN', 'My keyboard is broken', 'High', 'Dear IT, my keyboard is broken. Could you kinldy provide me a replacement ?', CURDATE(), 'AUTOMATIC_FILL', '2', '1', '1');
INSERT INTO `tickets` (`status`, `subject`, `priority`, `message`, `created_at`, `created_by`,`creator_id`,`assignee_id`,`assignee_derpartment_id`) VALUES ('OPEN', 'Video is too long', 'Normal', 'Lin, could you please reduce the video from yesterday ? It needs to be less than 5 minutes. Thank you', CURDATE(), 'AUTOMATIC_FILL', '2', '5', '5');
INSERT INTO `tickets` (`status`, `subject`, `priority`, `message`, `created_at`, `created_by`,`creator_id`,`assignee_id`,`assignee_derpartment_id`) VALUES ('OPEN', 'Ideas needed', 'Normal', 'Tao, what do you think of the presentation attached ? Thank you', CURDATE(), 'AUTOMATIC_FILL', '5', '3', '3');
INSERT INTO `tickets` (`status`, `subject`, `priority`, `message`, `created_at`, `created_by`,`creator_id`,`assignee_id`,`assignee_derpartment_id`) VALUES ('OPEN', 'Install Software', 'Normal', 'Dear IT, I need to install a plug-in for Excel. My TV is 123456789', CURDATE(), 'AUTOMATIC_FILL', '2', '6','1');
INSERT INTO `tickets` (`status`, `subject`, `priority`, `message`, `created_at`, `created_by`,`creator_id`,`assignee_id`,`assignee_derpartment_id`) VALUES ('OPEN', 'Instagram Views', 'High', 'URGENT - Patricia, correct the last post ASAP.', CURDATE(), 'AUTOMATIC_FILL', '3', '3', '3');